require 'rails_helper'

RSpec.describe "pagers/page1.html.haml", :type => :view do

  it 'have video tag (include source and p tags) generated by helper' do
    render
    expect(rendered).to have_tag 'video#my_video.video-js.vjs-default-skin.my_video_class' do
      with_tag 'source', count: 2
      with_tag 'track', count: 2
      with_tag 'p.vjs-no-js', text: /Customize Message when js is not woking/
    end
  end

end
